# Generated by Django 2.2 on 2019-06-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190619_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='tag_object',
            new_name='content_object',
        ),
    ]
