# Generated by Django 2.2 on 2019-06-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190619_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='content_object',
            new_name='page',
        ),
    ]
