# Generated by Django 2.2 on 2019-06-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190619_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='page',
            new_name='content_object',
        ),
    ]
